
// Fallback inventory data in case API fails
export const FALLBACK_INVENTORY_DATA = [
    // Living Room Items
    { category: "Living Room", item_name: 'TV up to 45"', average_volume: 0.1 },
    { category: "Living Room", item_name: 'TV up to 75"', average_volume: 0.2 },
    { category: "Living Room", item_name: "TV Stand", average_volume: 0.3 },
    { category: "Living Room", item_name: "Desk Standard", average_volume: 0.5 },
    { category: "Living Room", item_name: "Desk Large", average_volume: 0.75 },
    { category: "Living Room", item_name: "Armchair", average_volume: 1.0 },
    { category: "Living Room", item_name: "2 Seater Sofa", average_volume: 1.5 },
    { category: "Living Room", item_name: "3 Seater Sofa", average_volume: 2.0 },
    { category: "Living Room", item_name: "4 Seater Sofa", average_volume: 2.5 },
    { category: "Living Room", item_name: "Corner Sofa", average_volume: 3.5 },
    { category: "Living Room", item_name: "Cabinet Large", average_volume: 1.0 },
    { category: "Living Room", item_name: "Bookcase Large", average_volume: 0.8 },
    { category: "Living Room", item_name: "Grandfather Clock", average_volume: 0.6 },
    { category: "Living Room", item_name: "Other Medium Item", average_volume: 0.5 },
    { category: "Living Room", item_name: "Other Large Item", average_volume: 1.0 },
    { category: "Living Room", item_name: "Dining Table 4 Seater", average_volume: 1.0 },
    { category: "Living Room", item_name: "Dining Table 6 Seater", average_volume: 1.5 },
    { category: "Living Room", item_name: "Dining Table 8 Seater", average_volume: 2.0 },
    { category: "Living Room", item_name: "Dining Chair", average_volume: 0.15 },
    { category: "Living Room", item_name: "Misc Chairs ", average_volume: 0.25 },
    { category: "Living Room", item_name: "Sideboard ", average_volume: 1.2 },
    { category: "Living Room", item_name: "Coffee Table", average_volume: 0.3 },
    { category: "Living Room", item_name: "Cabinet Small", average_volume: 0.4 },
    { category: "Living Room", item_name: "Bookcase Small ", average_volume: 0.5 },
    { category: "Living Room", item_name: "Shelves Contents Only", average_volume: 0.1 },
    { category: "Living Room", item_name: "Ornaments Fragile ", average_volume: 0.1 },
    { category: "Living Room", item_name: "Plant Small ", average_volume: 0.05 },
    { category: "Living Room", item_name: "Plant Tall ", average_volume: 0.15 },
    { category: "Living Room", item_name: "Piano Upright", average_volume: 2.0 },

    // Kitchen Items
    { category: "Kitchen", item_name: "Fridge Under Counter", average_volume: 0.4 },
    { category: "Kitchen", item_name: "Fridge Freezer Upright", average_volume: 0.7 },
    { category: "Kitchen", item_name: "Fridge Freezer American", average_volume: 1.2 },
    { category: "Kitchen", item_name: "Freezer Under Counter", average_volume: 0.4 },
    { category: "Kitchen", item_name: "Freezer Chest", average_volume: 0.8 },
    { category: "Kitchen", item_name: "Washing Machine", average_volume: 0.6 },
    { category: "Kitchen", item_name: "Tumble Dryer", average_volume: 0.6 },
    { category: "Kitchen", item_name: "Cooker Standard", average_volume: 0.5 },
    { category: "Kitchen", item_name: "Dishwasher", average_volume: 0.6 },
    { category: "Kitchen", item_name: "Other Medium Item Kitchen", average_volume: 0.5 },
    { category: "Kitchen", item_name: "Other Large Item Kitchen", average_volume: 1.0 },
    { category: "Kitchen", item_name: "Kitchen Dining Table 4 Seater", average_volume: 1.0 },
    { category: "Kitchen", item_name: "Kitchen Dining Table 6 Seater", average_volume: 1.5 },
    { category: "Kitchen", item_name: "Kitchen Dining Table 8 Seater", average_volume: 2.0 },
    { category: "Kitchen", item_name: "Kitchen Dining Chair", average_volume: 0.15 },
    { category: "Kitchen", item_name: "Misc Chairs Kitchen", average_volume: 0.25 },
    { category: "Kitchen", item_name: "Ornaments Kitchen", average_volume: 0.1 },
    { category: "Kitchen", item_name: "Plant Small Kitchen", average_volume: 0.05 },
    { category: "Kitchen", item_name: "Plant Tall Kitchen", average_volume: 0.15 },
    { category: "Kitchen", item_name: "Kitchen Bin", average_volume: 0.1 },
    { category: "Kitchen", item_name: "General Small Medium Kitchen", average_volume: 0.2 },

    // Bathroom/Hallway Items
    { category: "Other / Bathroom / Hallway", item_name: "Sideboard Bathroom", average_volume: 1.2 },
    { category: "Other / Bathroom / Hallway", item_name: "Other Medium Bathroom", average_volume: 0.5 },
    { category: "Other / Bathroom / Hallway", item_name: "Other Large Bathroom", average_volume: 1.0 },
    { category: "Other / Bathroom / Hallway", item_name: "Bookcase Large Bathroom", average_volume: 0.8 },
    { category: "Other / Bathroom / Hallway", item_name: "Exercise Bike Hallway", average_volume: 0.8 },
    { category: "Other / Bathroom / Hallway", item_name: "Piano Upright Hallway", average_volume: 2.0 },
    { category: "Other / Bathroom / Hallway", item_name: "Cross Trainer Hallway", average_volume: 1.5 },
    { category: "Other / Bathroom / Hallway", item_name: "Treadmill Hallway", average_volume: 1.5 },
    { category: "Other / Bathroom / Hallway", item_name: "Bookcase Small Bathroom", average_volume: 0.5 },
    { category: "Other / Bathroom / Hallway", item_name: "Ornaments Bathroom", average_volume: 0.1 },
    { category: "Other / Bathroom / Hallway", item_name: "Plant Small Bathroom", average_volume: 0.05 },
    { category: "Other / Bathroom / Hallway", item_name: "Plant Tall Bathroom", average_volume: 0.15 },
    { category: "Other / Bathroom / Hallway", item_name: "General Small Bathroom", average_volume: 0.2 },

    // Garden/Garage Items
    { category: "Garden / Garage / Loft", item_name: "Garden Table", average_volume: 0.8 },
    { category: "Garden / Garage / Loft", item_name: "Garden Storage Box", average_volume: 1.0 },
    { category: "Garden / Garage / Loft", item_name: "Other Medium Garden", average_volume: 0.5 },
    { category: "Garden / Garage / Loft", item_name: "Other Large Garden", average_volume: 1.0 },
    { category: "Garden / Garage / Loft", item_name: "Shelving Unit Large", average_volume: 0.7 },
    { category: "Garden / Garage / Loft", item_name: "Exercise Bike Garden", average_volume: 0.8 },
    { category: "Garden / Garage / Loft", item_name: "Cross Trainer Garden", average_volume: 1.5 },
    { category: "Garden / Garage / Loft", item_name: "Treadmill Garden", average_volume: 1.5 },
    { category: "Garden / Garage / Loft", item_name: "Lawnmower", average_volume: 0.4 },
    { category: "Garden / Garage / Loft", item_name: "Fridge Freezer Garden", average_volume: 0.7 },
    { category: "Garden / Garage / Loft", item_name: "Freezer Chest Garden", average_volume: 0.8 },
    { category: "Garden / Garage / Loft", item_name: "BBQ Standard", average_volume: 0.6 },
    { category: "Garden / Garage / Loft", item_name: "Garden Tools Small", average_volume: 0.1 },
    { category: "Garden / Garage / Loft", item_name: "Garden Tools Large", average_volume: 0.25 },
    { category: "Garden / Garage / Loft", item_name: "Bookcase Small Garden", average_volume: 0.5 },
    { category: "Garden / Garage / Loft", item_name: "Garden Ornaments", average_volume: 0.15 },
    { category: "Garden / Garage / Loft", item_name: "Plant Small Garden", average_volume: 0.05 },
    { category: "Garden / Garage / Loft", item_name: "Plant Tall Garden", average_volume: 0.15 },
    { category: "Garden / Garage / Loft", item_name: "General Small Garden", average_volume: 0.2 },
    { category: "Garden / Garage / Loft", item_name: "Garden Shed Dismantled", average_volume: 5.0 },

    // Bedroom Items
    { category: "Bedroom", item_name: "Single Bed", average_volume: 1.0 },
    { category: "Bedroom", item_name: "Double Bed", average_volume: 1.5 },
    { category: "Bedroom", item_name: "KingSize Bed", average_volume: 2.0 },
    { category: "Bedroom", item_name: "Mattress Single", average_volume: 0.6 },
    { category: "Bedroom", item_name: "Mattress Double", average_volume: 0.8 },
    { category: "Bedroom", item_name: "Mattress KingSize", average_volume: 1.0 },
    { category: "Bedroom", item_name: "Cot", average_volume: 0.4 },
    { category: "Bedroom", item_name: "Bunk Bed", average_volume: 2.5 },
    { category: "Bedroom", item_name: "Bedside Table", average_volume: 0.3 },
    { category: "Bedroom", item_name: "TV 45 Bedroom", average_volume: 0.1 },
    { category: "Bedroom", item_name: "TV 75 Bedroom", average_volume: 0.2 },
    { category: "Bedroom", item_name: "Misc Chairs Bedroom", average_volume: 0.25 },
    { category: "Bedroom", item_name: "Desk Standard Bedroom", average_volume: 0.5 },
    { category: "Bedroom", item_name: "Desk Large Bedroom", average_volume: 0.75 },
    { category: "Bedroom", item_name: "Chest Of 4 Drawers", average_volume: 0.7 },
    { category: "Bedroom", item_name: "Chest Of 6 Drawers", average_volume: 0.9 },
    { category: "Bedroom", item_name: "Chest Drawers Double", average_volume: 1.2 },
    { category: "Bedroom", item_name: "Wardrobe Single", average_volume: 1.0 },
    { category: "Bedroom", item_name: "Wardrobe Double", average_volume: 1.5 },
    { category: "Bedroom", item_name: "Wardrobe Triple", average_volume: 2.0 },
    { category: "Bedroom", item_name: "Wardrobe Quad", average_volume: 2.5 },
    { category: "Bedroom", item_name: "Sideboard Bedroom", average_volume: 1.2 },
    { category: "Bedroom", item_name: "Other Medium Bedroom", average_volume: 0.5 },
    { category: "Bedroom", item_name: "Other Large Bedroom", average_volume: 1.0 },
    { category: "Bedroom", item_name: "Bookcase Large Bedroom", average_volume: 0.8 },
    { category: "Bedroom", item_name: "Bookcase Small Bedroom", average_volume: 0.5 },
    { category: "Bedroom", item_name: "Suitcases", average_volume: 0.2 },
    { category: "Bedroom", item_name: "Ornaments Bedroom", average_volume: 0.1 },
    { category: "Bedroom", item_name: "Other Bedroom", average_volume: 0.2 },

    // Office Items
    { category: "Office", item_name: "Standing Desk (adjustable)", average_volume: 1.18 },
    { category: "Office", item_name: "Corner Desk (L-shape)", average_volume: 1.44 },
    { category: "Office", item_name: "Reception Desk (small)", average_volume: 0.79 },
    { category: "Office", item_name: "Reception Desk (large counter)", average_volume: 1.94 },
    { category: "Office", item_name: "Coffee Table (round)", average_volume: 0.2 },
    { category: "Office", item_name: "Side Table", average_volume: 0.12 },
    { category: "Office", item_name: "Training Table (folding)", average_volume: 0.41 },
    { category: "Office", item_name: "High Bar Table", average_volume: 0.4 },
    { category: "Office", item_name: "Ergonomic Chair", average_volume: 0.59 },
    { category: "Office", item_name: "Conference Chair (stackable)", average_volume: 0.23 },
    { category: "Office", item_name: "Bar Stool", average_volume: 0.22 },
    { category: "Office", item_name: "Reception Waiting Chair", average_volume: 0.41 },
    { category: "Office", item_name: "Lounge Armchair", average_volume: 0.65 },
    { category: "Office", item_name: "Bean Bag", average_volume: 0.34 },
    { category: "Office", item_name: "Metal Storage Locker", average_volume: 0.31 },
    { category: "Office", item_name: "Large Metal Cabinet (2-door)", average_volume: 0.73 },
    { category: "Office", item_name: "Mobile Pedestal (wheels)", average_volume: 0.12 },
    { category: "Office", item_name: "Compact Rolling File Rack", average_volume: 0.61 },
    { category: "Office", item_name: "Open Shelf Unit (wide)", average_volume: 0.84 },
    { category: "Office", item_name: "Desk Hutch", average_volume: 0.3 },
    { category: "Office", item_name: "Document Sorter (multi-level)", average_volume: 0.05 },
    { category: "Office", item_name: "Laptop (boxed)", average_volume: 0.01 },
    { category: "Office", item_name: "Dual Monitor Arm", average_volume: 0.04 },
    { category: "Office", item_name: "UPS Battery Unit", average_volume: 0.03 },
    { category: "Office", item_name: "Server (rack-mounted)", average_volume: 0.09 },
    { category: "Office", item_name: "Desk Phone", average_volume: 0.005 },
    { category: "Office", item_name: "Projector", average_volume: 0.0075 },
    { category: "Office", item_name: "Projector Screen (rolled)", average_volume: 0.03 },
    { category: "Office", item_name: "Router / Switch (boxed)", average_volume: 0.006 },
    { category: "Office", item_name: "Large Whiteboard", average_volume: 0.108 },
    { category: "Office", item_name: "Corkboard", average_volume: 0.054 },
    { category: "Office", item_name: "Wall Clock", average_volume: 0.009 },
    { category: "Office", item_name: "Artificial Plant (tall)", average_volume: 0.24 },
    { category: "Office", item_name: "Plant (medium pot)", average_volume: 0.04 },
    { category: "Office", item_name: "Coat Stand", average_volume: 0.45 },
    { category: "Office", item_name: "Floor Lamp", average_volume: 0.14 },
    { category: "Office", item_name: "Fridge (under-counter)", average_volume: 0.26 },
    { category: "Office", item_name: "Full-Size Fridge", average_volume: 0.88 },
    { category: "Office", item_name: "Microwave", average_volume: 0.04 },
    { category: "Office", item_name: "Kettle (boxed)", average_volume: 0.02 },
    { category: "Office", item_name: "Water Cooler Dispenser", average_volume: 0.12 },
    { category: "Office", item_name: "Dining Table", average_volume: 0.84 },
    { category: "Office", item_name: "Dining Chair", average_volume: 0.18 },
    { category: "Office", item_name: "Small Moving Box", average_volume: 0.036 },
    { category: "Office", item_name: "Medium Moving Box", average_volume: 0.097 },
    { category: "Office", item_name: "Large Moving Box", average_volume: 0.129 },
    { category: "Office", item_name: "Extra-Large Moving Box", average_volume: 0.226 },
    { category: "Office", item_name: "Archive Document Box", average_volume: 0.032 },
    { category: "Office", item_name: "Heavy-Duty Crate", average_volume: 0.072 },
    { category: "Office", item_name: "Industrial Crate", average_volume: 0.14 },
    { category: "Office", item_name: "IT Equipment Crate", average_volume: 0.24 },
    { category: "Office", item_name: "File Storage Crate", average_volume: 0.126 },
    { category: "Office", item_name: "Wardrobe Box", average_volume: 0.33 },
    { category: "Office", item_name: "Pallet Crate", average_volume: 1.2 },
    { category: "Office", item_name: "Euro Pallet Box", average_volume: 0.96 },
    { category: "Office", item_name: "Half-Size Pallet Box", average_volume: 0.288 },
    { category: "Office", item_name: "Shredder (small)", average_volume: 0.04 },
    { category: "Office", item_name: "Shredder (large)", average_volume: 0.18 },
    { category: "Office", item_name: "Cardboard Archive Box", average_volume: 0.03 },
    { category: "Office", item_name: "Coat Hanger Rail", average_volume: 0.75 },
    { category: "Office", item_name: "Cleaning Cart", average_volume: 0.45 },
    { category: "Office", item_name: "Vacuum Cleaner", average_volume: 0.14 },
    { category: "Office", item_name: "Portable Partition Panel", average_volume: 0.135 },
    { category: "Office", item_name: "Mobile Whiteboard", average_volume: 1.4 },

    // Gym Items
    { category: "Gym", item_name: "Treadmill (commercial)", average_volume: 2.7 },
    { category: "Gym", item_name: "Elliptical Trainer", average_volume: 2.86 },
    { category: "Gym", item_name: "Spin Bike", average_volume: 0.94 },
    { category: "Gym", item_name: "Upright Exercise Bike", average_volume: 0.72 },
    { category: "Gym", item_name: "Rowing Machine", average_volume: 0.83 },
    { category: "Gym", item_name: "Stair Climber", average_volume: 2.46 },
    { category: "Gym", item_name: "Smith Machine", average_volume: 6.0 },
    { category: "Gym", item_name: "Cable Crossover", average_volume: 0.7 },
    { category: "Gym", item_name: "Lat Pulldown Machine", average_volume: 3.96 },
    { category: "Gym", item_name: "Seated Row Machine", average_volume: 2.64 },
    { category: "Gym", item_name: "Chest Press Machine", average_volume: 2.52 },
    { category: "Gym", item_name: "Leg Press (45°)", average_volume: 3.28 },
    { category: "Gym", item_name: "Leg Extension / Curl Combo", average_volume: 1.96 },
    { category: "Gym", item_name: "Dumbbell Rack", average_volume: 1.2 },
    { category: "Gym", item_name: "Dumbbell Set", average_volume: 0.025 },
    { category: "Gym", item_name: "Barbell Rack", average_volume: 1.44 },
    { category: "Gym", item_name: "Weight Plates", average_volume: 0.11 },
    { category: "Gym", item_name: "Incline Bench", average_volume: 1.01 },
    { category: "Gym", item_name: "Flat Bench", average_volume: 0.32 },
    { category: "Gym", item_name: "Adjustable Bench", average_volume: 0.39 },
    { category: "Gym", item_name: "Power Rack", average_volume: 0.5 },
    { category: "Gym", item_name: "Kettlebell", average_volume: 0.019 },
    { category: "Gym", item_name: "Medicine Ball", average_volume: 0.043 },
    { category: "Gym", item_name: "Plyometric Box", average_volume: 0.34 },
    { category: "Gym", item_name: "Punching Bag (standing)", average_volume: 0.65 },
    { category: "Gym", item_name: "Punching Bag (hanging)", average_volume: 0.19 },
    { category: "Gym", item_name: "Yoga Mat", average_volume: 0.028 },
    { category: "Gym", item_name: "Foam Roller", average_volume: 0.01 },
    { category: "Gym", item_name: "Balance Ball", average_volume: 0.27 },
];
